export class Probability {
  address: string;
  city: string;
  created_at: number;
  creatorparentid: number;
  deviceid: any;
  email: string;
  id: number;
  name: string;
  phone: string;
  probability: any;
  published_at: string;
  state: string;
  updated_at: string;
  zipcode: number;
  data: any;
  ispermitraised: boolean;
  isassessmentraised: boolean;
  isproposalraised: boolean;
  issurveyraised: boolean;
  probabilityscore: number;
  county: string;
  solarcapacity: any;
  solararrayarea: any;
  numberofdetachbuildings: number;
  numberofroofs: number;
  annualprod: any;
  contracttype: string;
}
