import { Activity } from "./activity";
import { Comment } from "./comment";
import { Design } from "./design";
import { InverterMake } from "./invertermake";
import { InverterModel } from "./invertermodel";
import { ModuleMake } from "./modulemake";
import { ModuleModel } from "./modulemodel";
import { RoofMaterial } from "./roofmaterial";
import { UploadedFile } from "./uploadedfile";
import { User } from "./user";
import { Utility } from "./utility";

export class Survey {
  id: number;
  chatid: string;
  name: string;
  email: string;
  phonenumber: number;
  latitude: number;
  longitude: number;
  datetime: string;
  createdby: User;
  address: string;
  jobtype: string;
  city: string;
  state: string;
  country: string;
  source: string;
  pvmeter: boolean;
  acdisconnect: boolean;
  assignedto: User;
  mspimages: UploadedFile[];
  utilitymeterimages: UploadedFile[];
  pvinverterimages: UploadedFile[];
  pvmeterimages: UploadedFile[];
  acdisconnectimages: UploadedFile[];
  roofimages: UploadedFile[];
  atticimages: UploadedFile[];
  existingsubpanelimages: UploadedFile[];
  roofdimensionimages: UploadedFile[];
  rooftilt: number;
  obstaclesimages: UploadedFile[];
  obstaclesdimensionsimages: UploadedFile[];
  appliancesimages: UploadedFile[];
  solarpanelsimages: UploadedFile[];
  groundimages: UploadedFile[];
  electricalslocation: UploadedFile;
  surveypdf: UploadedFile;
  distancebetweentworafts: number;
  sizeofsingleraft: string;
  loadsnottobebackedup: string;
  additionalnotes: string;
  newconstruction: boolean;
  existingsolarsystem: boolean;
  existingsolarsystemdetails: string;
  msplocation: string;
  mainbreakersize: number;
  msprating: number;
  mspbreaker: string;
  subpanellocation: string;
  subpanelrating: number;
  subpanelmainbreakersize: number;
  subpanelbreaker: string;
  utilitymeter: string;
  utility: Utility;
  pvinverterlocation: string;
  invertermake: InverterMake;
  invertermodel: InverterModel;
  modulemake: ModuleMake;
  modulemodel: ModuleModel;
  numberofmodules: number;
  batterybackup: string;
  interconnection: string;
  servicefeedsource: string;
  status: string;
  outsourcedto: User;
  isoutsourced: string;
  requestdeclinereason: string;
  reviewissues: string;
  reviewassignedto: User;
  reviewstarttime: string;
  activities: Activity[];
  comments: Comment[];
  postalcode: string;
  created_at: string;
  updated_at: string;
  isdesignraised: boolean;
  framing: string;
  framingsize: string;
  designid: number;
  prelimdesignsurvey: Design;
  batterysystem: string;
  hoadetails: string;
  hoaattachments: UploadedFile[];
  esid: number;
  groupchatpassword: string;
  //Dynamic Content
  currentstatus: string;
  isoverdue: boolean;
  formattedtime: string;
  formattedupdatedat: string;
  formattedjobtype: string;
  unreadmessagecount = 0;
  roofmaterial: RoofMaterial;
  utilitybillfront: UploadedFile;
  utilitybillback: UploadedFile;
  meternumber: string;
  mpurequired: string;
  projecttype: string;
  raiserequestattachment: UploadedFile[];
  raiserequestreason: string;
}
